name: Nix
permissions:
  contents: write
on:
  pull_request: null
  push:
    branches:
      - main
jobs:
  x86_64-linux---camkes-deps:
    name: Build x86_64-linux.camkes-deps
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---concurrencytest
      - x86_64-linux---seL4-deps
      - x86_64-linux---guardonce
      - x86_64-linux---pyfdt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.camkes-deps --print-build-logs
  x86_64-linux---concurrencytest:
    name: Build x86_64-linux.concurrencytest
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.concurrencytest --print-build-logs
  x86_64-linux---guardonce:
    name: Build x86_64-linux.guardonce
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.guardonce --print-build-logs
  x86_64-linux---pyfdt:
    name: Build x86_64-linux.pyfdt
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.pyfdt --print-build-logs
  x86_64-linux---seL4-deps:
    name: Build x86_64-linux.seL4-deps
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---guardonce
      - x86_64-linux---pyfdt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-deps --print-build-logs
  x86_64-linux---seL4-kernel-arm:
    name: Build x86_64-linux.seL4-kernel-arm
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-arm --print-build-logs
  x86_64-linux---seL4-kernel-arm-hyp:
    name: Build x86_64-linux.seL4-kernel-arm-hyp
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-arm-hyp --print-build-logs
  x86_64-linux---seL4-kernel-arm-mcs:
    name: Build x86_64-linux.seL4-kernel-arm-mcs
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-arm-mcs --print-build-logs
  x86_64-linux---seL4-kernel-riscv64:
    name: Build x86_64-linux.seL4-kernel-riscv64
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
      - x86_64-linux---seL4-deps
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-riscv64 --print-build-logs
  x86_64-linux---seL4-kernel-riscv64-mcs:
    name: Build x86_64-linux.seL4-kernel-riscv64-mcs
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---guardonce
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-riscv64-mcs --print-build-logs
  x86_64-linux---seL4-kernel-x64:
    name: Build x86_64-linux.seL4-kernel-x64
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-kernel-x64 --print-build-logs
  x86_64-linux---seL4-moritz-fork-arm:
    name: Build x86_64-linux.seL4-moritz-fork-arm
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---pyfdt
      - x86_64-linux---seL4-deps
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-moritz-fork-arm --print-build-logs
  x86_64-linux---seL4-moritz-fork-arm-hyp:
    name: Build x86_64-linux.seL4-moritz-fork-arm-hyp
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---guardonce
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-moritz-fork-arm-hyp --print-build-logs
  x86_64-linux---seL4-moritz-fork-arm-mcs:
    name: Build x86_64-linux.seL4-moritz-fork-arm-mcs
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---pyfdt
      - x86_64-linux---seL4-deps
      - x86_64-linux---guardonce
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-moritz-fork-arm-mcs --print-build-logs
  x86_64-linux---seL4-moritz-fork-x64:
    name: Build x86_64-linux.seL4-moritz-fork-x64
    runs-on:
      - ubuntu-latest
    needs:
      - x86_64-linux---seL4-deps
      - x86_64-linux---pyfdt
      - x86_64-linux---guardonce
      - x86_64-linux---seL4-test-source
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-moritz-fork-x64 --print-build-logs
  x86_64-linux---seL4-test-source:
    name: Build x86_64-linux.seL4-test-source
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#packages.x86_64-linux.seL4-test-source --print-build-logs
  x86_64-linux---check:
    name: Run Nix checks on x86_64-linux
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check
        run: nix flake check . --print-build-logs
